version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kyc_db
    ports:
      - "5432:5432"
    networks:
      - my_network

  fastapi_app:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://user:password@postgres_db:5432/kyc_db"
    command: >
      sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    networks:
      - my_network
  frontend:
    build:
      context: ../frontend  # Replace with the actual path to your frontend repo
      dockerfile: Dockerfile
    container_name: frontend_app
    depends_on:
      - fastapi_app
    ports:
      - "3000:3000"
    networks:
      - my_network




networks:
  my_network:
