"""check alembic

Revision ID: 6adecaba4ae3
Revises: 
Create Date: 2025-02-15 09:48:11.369956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6adecaba4ae3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_records', sa.Column('ifsc_code', sa.String(), nullable=True))
    op.drop_column('kyc_records', 'ifsc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_records', sa.Column('ifsc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('kyc_records', 'ifsc_code')
    # ### end Alembic commands ###
